### PR TITLE
chore: update dotnet sdk to 6.0.405

### PR DESCRIPTION
**Pull request by hjgraca**
Issue number: #203 

## Summary

update dotnet sdk to 6.0.405

### Changes

.NET 6.0.13 (6.0.405 sdk) release carries security fixes.
Official release https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.13/6.0.13.md?WT.mc_id=dotnet-35129-website

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

Please leave checklist items unchecked if they do not apply to your change.

* [x] [Meets tenets criteria](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by hjgraca** [comment]
Getting CodeCov 404 error. From what I could find online https://github.com/codecov/codecov-action/issues/598, I think we might need to generate a new token...

**Comment by sliedig** [comment]
> Getting CodeCov 404 error. From what I could find online [codecov/codecov-action#598](https://github.com/codecov/codecov-action/issues/598), I think we might need to generate a new token...

New token generated

**Comment by sliedig** [comment]
Test seems to be failing https://github.com/awslabs/aws-lambda-powertools-dotnet/actions/runs/4116108873/jobs/7123440610#step:6:590

**Comment by hjgraca** [comment]
> Test seems to be failing https://github.com/awslabs/aws-lambda-powertools-dotnet/actions/runs/4116108873/jobs/7123440610#step:6:590

   Mock<ISystemWrapper:78> (v):

      ISystemWrapper.LogLine("{"cold_start":true,"correlation_id":"528746ff-75ec-4124-807f-81961f76e9d8","timestamp":"2023-02-08T12:57:47.9053619Z","level":"Information","service":"0e67ec31-9ca0-4183-b31e-6524bd23dd93","name":"880b0526-6828-4639-ae45-e919ba52b9a7","message":{"name":"Test Object","stream":"XpiVwfRYvy\u002Bapw=="}}")

  Stack Trace:
     at Moq.Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage) in C:\projects\moq4\src\Moq\Mock.cs:line 330
   at Moq.Mock`1.Verify(Expression`1 expression, Times times) in C:\projects\moq4\src\Moq\Mock`1.cs:line 727
   at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times) in C:\projects\moq4\src\Moq\Mock`1.cs:line 741
   at AWS.Lambda.Powertools.Logging.Tests.PowertoolsLoggerTest.Log_WhenMemoryStream_LogsBase64String() in /home/runner/work/aws-lambda-powertools-dotnet/aws-lambda-powertools-dotnet/libraries/tests/AWS.Lambda.Powertools.Logging.Tests/PowertoolsLoggerTest.cs:line 1170

Yeah this one test seems very flacky, it worked twice in a row with the new Moq version but guess not.. I'll have a look

**Comment by amirkaws** [comment]
I rerun the build, was successful.

**Review by sliedig — APPROVED** [review]

**Pull request merged**
