### PR TITLE
docs(home): add discord invitation link

### PR DESCRIPTION
**Pull request by sthuber90**
**Issue number:** #154 

### Changes

> Please provide a summary of what's being changed

Replace occurrences of Slack invitation links with links to the new Discord space.

### User experience

> Please share what the user experience looks like before and after this change

N/A

## Checklist

Please leave checklist items unchecked if they do not apply to your change.

* [x] [Meets tenets criteria](https://awslabs.github.io/aws-lambda-powertools-dotnet/tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-dotnet/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

-----
[View rendered README.md](https://github.com/sthuber90/aws-lambda-powertools-dotnet/blob/add-discord-link-154/README.md)
[View rendered docs/index.md](https://github.com/sthuber90/aws-lambda-powertools-dotnet/blob/add-discord-link-154/docs/index.md)

### CODE REVIEW

**Review by jeastham1993 — APPROVED** [review]

**Review by sliedig — CHANGES_REQUESTED** [review]
Hello @sthuber90, thanks for your submission!

Can you please add a second link to the #dotnet channel in Discord too please. 

Link is: https://discord.com/channels/1006478942305263677/1006527454174773269

**Comment by sthuber90** [comment]
@sliedig do you want the second link next to the invitation link or do you want to replace the invitation link? I think the channel link will only work, if you have an account already, corret?

**Comment by sliedig** [comment]
> @sliedig do you want the second link next to the invitation link or do you want to replace the invitation link? I think the channel link will only work, if you have an account already, corret?

Ah, yeah fair enough. Maybe we'll leave it for now.

**Review by sliedig — APPROVED** [review]
Thank you @sthuber90 for your help putting this together

**Pull request merged**
